sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - master

install:
  - >
    composer install;
    composer update --with-dependencies --prefer-stable --prefer-dist;
    composer show;

script:
  - phpunit --coverage-text
